<?php

namespace Database\Seeders;

use App\Defines\Status;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LessonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('lessons')->insert([
            // JS
            [
                'name' => 'Mở đầu về Javascript',
                'slug' => 'mo-dau-ve-javascript',
                'description' => 'Bài học mở đầu hoy',
                'chapter_id' => 1,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
             ],
            [
                'name' => 'Biến trong javascript',
                'slug' => 'bien-trong-javascript',
                'description' => 'Bài học mở đầu hoy',
                'chapter_id' => 1,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Hằng Javascript',
                'slug' => 'hang-trong-javascript',
                'description' => 'Bài học mở đầu hoy',
                'chapter_id' => 1,
                'order' => 3,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Vòng lặp trong Javascript',
                'slug' => 'vong-lap-trong-javascript',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 2,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Hàm trong Javascript',
                'slug' => 'ham-trong-javascript',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 2,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Các loại fuction',
                'slug' => 'cac-loai-fuction',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 2,
                'order' => 3,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'HTML DOM',
                'slug' => 'html-dom',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 3,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'DOM Events',
                'slug' => 'dom-events',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 3,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Form Validation',
                'slug' => 'form-validation',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 3,
                'order' => 3,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // NodeJS
            [
                'name' => 'Bài 1 NodeJS',
                'slug' => 'bai-1-nodejs',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 4,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bài 2 NodeJS',
                'slug' => 'bai-2-nodejs',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 4,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bài 3 NodeJS',
                'slug' => 'bai-3-nodejs',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 4,
                'order' => 3,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bài 4 NodeJS',
                'slug' => 'bai-4-nodejs',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 5,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bài 5 NodeJS',
                'slug' => 'bai-5-nodejs',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 5,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bài 6 NodeJS',
                'slug' => 'bai-6-nodejs',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 5,
                'order' => 3,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bài 7 NodeJS',
                'slug' => 'bai-7-nodejs',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 6,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bài 8 NodeJS',
                'slug' => 'bai-8-nodejs',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 6,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bài 9 NodeJS',
                'slug' => 'bai-9-nodejs',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 6,
                'order' => 3,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Huong doi tuong
            [
                'name' => 'Nhập môn hướng đối tượng',
                'slug' => 'nhap-mon-huong-doi-tuong',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 7,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Các tính chất của hướng đối tượng',
                'slug' => 'cac-tinh-chat-cua-huong-doi-tuong',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 7,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tính đóng gói',
                'slug' => 'tinh-dong-goi',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 8,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tính kế thừa',
                'slug' => 'tinh-ke-thua',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 8,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tính đa hình',
                'slug' => 'tinh-da-hinh',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 8,
                'order' => 3,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tính trừu tượng',
                'slug' => 'tinh-truu-tuong',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 8,
                'order' => 4,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lập trình game sử dụng OOP',
                'slug' => 'lap-trinh-game-du-dung-oop',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 9,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Toan 10
            [
                'name' => 'Giới thiệu toán 10',
                'slug' => 'gioi-thieu-toan-10',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 10,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mệnh đề - Tập hợp',
                'slug' => 'menh-de-tap-hop',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 11,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Phương trình, hệ phương trình',
                'slug' => 'phuong-trinh-he-phuong-trinh',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 11,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bất đẳng thức, bất phương trình',
                'slug' => 'bat-dang-thuc-bat-phuong-trinh',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 11,
                'order' => 3,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Toan 11
            [
                'name' => 'Giới thiệu toán 11',
                'slug' => 'gioi-thieu-toan-11',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 12,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Hàm số lượng giác',
                'slug' => 'ham-so-luong-giac',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 13,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tổ hợp xác suất',
                'slug' => 'to-hop-xac-suat',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 13,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Đạo hàm',
                'slug' => 'dao-ham',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 13,
                'order' => 3,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Toan 12
            [
                'name' => 'Giới thiệu toán 12',
                'slug' => 'gioi-thieu-toan-12',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 14,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nguyên hàm, tích phân',
                'slug' => 'nguyen-ham-tich-phan',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 15,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Số phức',
                'slug' => 'so-phuc',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 15,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Phương pháp tọa độ trong không gian',
                'slug' => 'phuong-phap-toa-do-trong-khong-gian',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 15,
                'order' => 3,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Dai so
            [
                'name' => 'Không gian vecto R',
                'slug' => 'khong-gian-vecto-r',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 16,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tổ hợp tuyến tính',
                'slug' => 'to-hop-tuyen-tinh',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 16,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Không gian vector con',
                'slug' => 'khong-gian-vector-con',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 16,
                'order' => 3,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ma trận',
                'slug' => 'ma-tran',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 17,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Định thức',
                'slug' => 'dinh-thuc',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 17,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Hệ phương trình tuyến tính',
                'slug' => 'he-phuong-trinh-tuyen-tinh',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 18,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mô hình cân bằng thị trường',
                'slug' => 'mo-hinh-can-bang-thi-truong',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 18,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Giai tich
            [
                'name' => 'Tích phân vô hướng',
                'slug' => 'tich-phan-vo-huong',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 19,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tích phân có hướng',
                'slug' => 'tich-phan-co-huong',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 20,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Ly thuyet on dinh
            [
                'name' => 'LTOD bài 1',
                'slug' => 'ltod-bai-1',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 21,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'LTOD bài 2',
                'slug' => 'ltod-bai-2',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 21,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'LTOD bài 3',
                'slug' => 'ltod-bai-3',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 22,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'LTOD bài 4',
                'slug' => 'ltod-bai-4',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 22,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Giai tich phi tuyen
            [
                'name' => 'GTPT bài 1',
                'slug' => 'gtpt-bai-1',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 23,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'GTPT bài 2',
                'slug' => 'gtpt-bai-2',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 23,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'GTPT bài 3',
                'slug' => 'gtpt-bai-3',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 23,
                'order' => 3,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'GTPT bài 4',
                'slug' => 'gtpt-bai-4',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 24,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'GTPT bài 5',
                'slug' => 'gtpt-bai-5',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 24,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'GTPT bài 6',
                'slug' => 'gtpt-bai-6',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 24,
                'order' => 3,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Kinh te chinh tri
            [
                'name' => 'Đối tượng nghiên cứu',
                'slug' => 'doi-tuong-nghien-cuu',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 25,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Phương pháp nghiên cứu',
                'slug' => 'phuong-phap-nghien-cuu',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 25,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chức năng',
                'slug' => 'chuc-nang',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 26,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Kinh te quoc te
            [
                'name' => 'Nhập môn kinh tế quốc tế',
                'slug' => 'nhap-mon-kinh-te-quoc-te',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 27,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Các khái niệm cơ bản',
                'slug' => 'cac-khai-niem-co-ban',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 28,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Hội nhập quốc tế',
                'slug' => 'hoi-nhap-quoc-te',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 28,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Kinh te vi mo
            [
                'name' => 'Nhập môn kinh tế vi mô',
                'slug' => 'nhap-kinh-te-vi-mo',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 29,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Các công thức tính',
                'slug' => 'cac-cong-thuc-tinh',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 30,
                'order' => 1,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bài tập chuyên ngành',
                'slug' => 'bai-tap-chuyen-nganh',
                'description' => 'Vòng lặp nha',
                'chapter_id' => 30,
                'order' => 2,
                'video_url' => 'ScNsBpQ8KIg',
                'status' => Status::_PUBLISH,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
